const text = {
    win: [
        '“Sometimes by losing a battle you find a new way to win the war.” Donald Trump ',
        "I think you cheated",
        "What ist this?!",
        "Pure luck!",
        "I can't believe this happened to me!",
        "I thought I was unbeatable...",
        "You wont be able to repeat this, will you?",
        "Are you the CR7 of Rock, Paper, Scissors?",
        "Just beginners luck!",
        "Next time luck will be on my side.",
        "I've decided to let you win this time.",
        "Let's do a revenge.",
        "Can you give me any tips to improve?",
        "I can't lose... I don't believe it..",
        "It's ok, I'll win next time...",
        "You're in luck again.",
        "I can't believe you've done this!",
        "I gave this game away to cheer you up.",
        "That's impossible!",
        "Listen here, you little sh**",
        "No way you won!",
        "You won by this much 🤏",
        "How did you win again?!",
        "🖕",
        "😵‍💫",
        "😤",
        "🤬",
    ],
    tie: [
        "We need a tie-breaker.",
        "Some are lucky, others know how to play.",
        "Do you really think you can win the next round?!",
        "I can't believe this. We are always tying",
        "Try again, maybe you'll get lucky",
        "Give peace a chance.",
        "Next round I'll show you how it's done.",
        "We'll meet again.",
        "Perfectly balanced, like all things should be ",
        "Another tie 🤦",
        "Why did you have to make a tie?",
    ],
    lose: [
        "If you learn from a loss you have not lost.",
        "In life, winning and losing will both happen. What is never acceptable is quitting.",
        "I'm the Cristiano Ronaldo of Rock Paper Scissors!",
        "Just give it another try.",
        "Winning is in my blood.",
        "Keep trying.",
        "Luck is with the brave.",
        "Come on, you can do better than this!",
        "You could have said, that you don't know anything about this game.",
        "Don't be sad.",
        "Next time you'll do better, I promise",
        "It's tougher than you thought, isn't it?",
        "Never give up.",
        "I'm the best, f*** the rest!",
        "Did the challenge already start?",
        "Oh come on, at least try!",
        "That was easy",
        "This is my winning dance! 💃",
        "Bye bye",
        "🤖",
        "🦾",
        "👾",
        "👋",
        "💤",
        "💪",
        "😁",
        "🥱",
        "🕺",
        "😭",
        "👎",
    ]
}